### PR TITLE
Fix: Call URLConnection#disconnect on same thread that created.

### PR DESCRIPTION
**Pull request by t-ae**
This PR includes:
- Modification of Request#cancel (Call URLConnection#disconnect on the thread that created).
- Update for Kotlin1.0.1-2.

(rebased correctly)

### CODE REVIEW

**Comment by koher** [comment]
> Each instance of HttpURLConnection may be used for one request/response pair. Instances of this class are not thread safe.
> -- [HttpURLConnection](http://developer.android.com/reference/java/net/HttpURLConnection.html)

It seems necessary to make it synchronized.

However, I want to avoid to introduce flags. They make states complicated exponentially. Using `synchronized(urlConnection) { .. }` seems better.

I also think `urlConnection.connect()` should be outside of `thread { ... }` to ensure that the `cancel` method, and `disconnect()` in it, is called after `connect()`ed.

**Comment by t-ae** [comment]
Call `urlConnection.connect()` outside `thread` may cause `NetworkOnMainThreadException`.
So I'll leave it inside.

**Comment by koher** [comment]
OK. Then we need a way to ensure calling `disconnect()` after `connect()`. Do you have any idea to do it without flags?

**Comment by t-ae** [comment]
I think we cannot specify whether `cancel()` called before `connect()` or not.
I have no idea but using flag ...

**Comment by koher** [comment]
I see. Seems no way without the flag. Let's revert to 767912f and pick the modification for `keepAlive`.

**Pull request merged**
